### PR TITLE
Resolving #3

### PR DESCRIPTION
**Pull request by snydergd**
Added options page with selection of default forum view, made that work, adding an event page for debugging and a shared js file for data that everything should have access to.

### CODE REVIEW

**Comment by dcrousso** [comment]
Hey @snydergd this is really awesome!  Thanks for helping out with this.  Unfortunately, my school doesn't use these features (or at least not in my classes so far), so if possible, do you mind uploading a few screenshots to show what this does (before/after)?  Thanks!

**Comment by snydergd** [comment]
Sure thing, @dcrousso.  Here is a link that I gets changed (of course, all similar links on the page get changed as well):
discussion_listing

Originally it goes to list view all the time, which looks like this:
list_view

As you can see, there's a link in the upper right to go to tree view, which looks like this (notice the little plus sign next to the post title to expand it):
tree_view

Now whether the link goes to list view or tree view depends on what is selected on the [new options page](chrome-extension://foeplnghmipjecdcmndapcmgjeiljedk/options.html) (I think that link should work).

Sorry, not very easy to capture in just screen shots.  I wish I could test it with more blackboard installations, but unfortunately this is the only one I have access to.

**Comment by dcrousso** [comment]
Thanks for uploading the images @snydergd!  I'm swamped with schoolwork right now, but I'll take a look  by the end of the week at the latest (just want to see what it does with USC's blackboard).  I'll let you know.

**Comment by snydergd** [comment]
Thanks for the update @dcrousso!  Hopefully it will play nicely with USC's blackboard.  I don't think I changed anything that would mess it up.  Glad to have someone else testing it though.  I look forward to hearing how it goes.  Good luck with your schoolwork.

**Comment by dcrousso** [comment]
Hey @snydergd sorry about this huge delay.  Just finished the semester, so I finally got a chance to take a look.  I have a few style changes, but otherwise it LGTM.

**Pull request merged**
